// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GraphUrlsEdgeDescriptionData, GraphUrlsEdgeDescriptionResponses, GraphUrlsNeighboursData, GraphUrlsNeighboursResponses, GraphUrlsSearchData, GraphUrlsSearchResponses, GraphUrlsShortestPathData, GraphUrlsShortestPathResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Neighbours
 */
export const graphUrlsNeighbours = <ThrowOnError extends boolean = false>(options: Options<GraphUrlsNeighboursData, ThrowOnError>) => (options.client ?? client).get<GraphUrlsNeighboursResponses, unknown, ThrowOnError>({ url: '/api/neighbours', ...options });

/**
 * Search
 */
export const graphUrlsSearch = <ThrowOnError extends boolean = false>(options: Options<GraphUrlsSearchData, ThrowOnError>) => (options.client ?? client).get<GraphUrlsSearchResponses, unknown, ThrowOnError>({ url: '/api/search', ...options });

/**
 * Edge Description
 */
export const graphUrlsEdgeDescription = <ThrowOnError extends boolean = false>(options: Options<GraphUrlsEdgeDescriptionData, ThrowOnError>) => (options.client ?? client).get<GraphUrlsEdgeDescriptionResponses, unknown, ThrowOnError>({ url: '/api/edge-description', ...options });

/**
 * Shortest Path
 */
export const graphUrlsShortestPath = <ThrowOnError extends boolean = false>(options: Options<GraphUrlsShortestPathData, ThrowOnError>) => (options.client ?? client).get<GraphUrlsShortestPathResponses, unknown, ThrowOnError>({ url: '/api/shortest-path', ...options });
