// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

/**
 * Neighbour
 */
export type Neighbour = {
    /**
     * Title
     */
    title: string;
    /**
     * Outward
     */
    outward: boolean;
    /**
     * Description
     */
    description: string | null;
};

/**
 * Artist
 */
export type Artist = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string | null;
};

/**
 * Edge
 */
export type Edge = {
    /**
     * Description
     */
    description: Array<string>;
};

/**
 * Path
 */
export type Path = {
    /**
     * Stops
     */
    stops: Array<string>;
};

export type GraphUrlsNeighboursData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Title
         */
        title: string;
    };
    url: '/api/neighbours';
};

export type GraphUrlsNeighboursResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<Neighbour>;
};

export type GraphUrlsNeighboursResponse = GraphUrlsNeighboursResponses[keyof GraphUrlsNeighboursResponses];

export type GraphUrlsSearchData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Name
         */
        name: string;
    };
    url: '/api/search';
};

export type GraphUrlsSearchResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<Artist>;
};

export type GraphUrlsSearchResponse = GraphUrlsSearchResponses[keyof GraphUrlsSearchResponses];

export type GraphUrlsEdgeDescriptionData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Source
         */
        source: string;
        /**
         * Target
         */
        target: string;
    };
    url: '/api/edge-description';
};

export type GraphUrlsEdgeDescriptionResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<Edge>;
};

export type GraphUrlsEdgeDescriptionResponse = GraphUrlsEdgeDescriptionResponses[keyof GraphUrlsEdgeDescriptionResponses];

export type GraphUrlsShortestPathData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Start Title
         */
        start_title: string;
        /**
         * End Title
         */
        end_title: string;
    };
    url: '/api/shortest-path';
};

export type GraphUrlsShortestPathResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<Path>;
};

export type GraphUrlsShortestPathResponse = GraphUrlsShortestPathResponses[keyof GraphUrlsShortestPathResponses];
