// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

/**
 * Neighbour
 */
export type Neighbour = {
    /**
     * Title
     */
    title: string;
    /**
     * Outward
     */
    outward: boolean;
};

/**
 * Artist
 */
export type Artist = {
    /**
     * Title
     */
    title: string;
};

export type GraphUrlsNeighboursData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Title
         */
        title: string;
    };
    url: '/api/neighbours';
};

export type GraphUrlsNeighboursResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<Neighbour>;
};

export type GraphUrlsNeighboursResponse = GraphUrlsNeighboursResponses[keyof GraphUrlsNeighboursResponses];

export type GraphUrlsSearchData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Name
         */
        name: string;
    };
    url: '/api/search';
};

export type GraphUrlsSearchResponses = {
    /**
     * Response
     *
     * OK
     */
    200: Array<Artist>;
};

export type GraphUrlsSearchResponse = GraphUrlsSearchResponses[keyof GraphUrlsSearchResponses];
